Parameters:
  AppName:
    Type: String
    Description: App name

  Environment:
    Type: String
    Description: Environment name

  DeploymentType:
    Type: String
    Description: Deployment tipi (bluegreen veya rolling)

  AppPort:
    Type: Number

  InstanceType:
    Type: String
    Description: EC2 instance tipi
    Default: t3.micro

  AmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Description: ECS-uyumlu AMI ID
    Default: /aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id

  ASGMin:
    Type: Number
  
  ASGMax:
    Type: Number
  
  ASGDesired:
    Type: Number
  
  ServiceDesired:
    Type: Number

Resources:
  EcsTaskDefStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub '{{resolve:ssm:/${AppName}/${Environment}/iac_bucket_url}}/compute/ecs/web-task-definition.yaml'
      Parameters:
        AppName: !Ref AppName
        Environment: !Ref Environment
        AppPort: !Ref AppPort

  EcsClusterStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub '{{resolve:ssm:/${AppName}/${Environment}/iac_bucket_url}}/compute/ecs/cluster.yaml'
      Parameters:
        AppName: !Ref AppName
        Environment: !Ref Environment
        InstanceType: !Ref InstanceType
        AmiId: !Ref AmiId
        ASGMin: !Ref ASGMin
        ASGMax: !Ref ASGMax
        ASGDesired: !Ref ASGDesired

  EcsServiceStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - EcsTaskDefStack
      - EcsClusterStack
    Properties:
      TemplateURL: !Sub '{{resolve:ssm:/${AppName}/${Environment}/iac_bucket_url}}/compute/ecs/web-service.yaml'
      Parameters:
        AppName: !Ref AppName
        Environment: !Ref Environment
        DeploymentType: !Ref DeploymentType
        AppPort: !Ref AppPort
        ServiceDesired: !Ref ServiceDesired