Parameters:
  AppName:
    Type: String
    Description: App name

  Environment:
    Type: String
    Description: Environment name

  BuildPurpose:
    Type: String
    Description: logical purpose of produced artifact

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${BuildPurpose}/${Environment}"
      ImageTagMutability: MUTABLE
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Expire untagged images after 30 days",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 30
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

  # Custom Resource to Trigger Lambda on Delete
  ECRImageCleaner:
    Type: Custom::DeleteECRImages
    Properties:
      ServiceToken:
        Fn::ImportValue: !Sub ${AppName}-${Environment}-ecr-image-delete-function
      RepositoryName: !Ref ECRRepository
      AccountId: !Ref AWS::AccountId

Outputs:
  RepositoryUri:
    Description: "ECR repository URI"
    Value: !GetAtt ECRRepository.RepositoryUri
    Export:
      Name: !Sub ${AppName}-${Environment}-${BuildPurpose}-ecr-uri