version: 0.2

env:
  variables:
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin "$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"

  build:
    commands:
      - echo Build Docker image...
      - docker build -t $REPO_NAME -f infrastructure/assets/db-init/ecs/Dockerfile infrastructure/assets/db-init/ecs
      # - docker tag $REPO_NAME/$BUILD_PURPOSE:$IMAGE_TAG $ECR_URI/$BUILD_PURPOSE:$IMAGE_TAG
      - docker tag $REPO_NAME:latest $ECR_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $ECR_URI:$IMAGE_TAG