AWSTemplateFormatVersion: '2010-09-09'
Description: CodeBuild project for ECS Pipeline

Parameters:
  AppName:
    Type: String
    Description: App name

  Environment:
    Type: String
    Description: Environment name

  GitRepoId:
    Type: String
    Description: owner/repo biçiminde GitHub repo ID'si

  GithubConnectionArn:
    Type: String
    Description: Github Connection ARN

  DeploymentType:
    Type: String
    Description: Deployment tipi (BlueGreen veya Rolling)

  ArtifactBucket:
    Type: String

  ContainerName:
    Type: String

  ContainerPort:
    Type: Number

Conditions:
  IsRolling: !Equals [!Ref DeploymentType, Rolling]
  IsBlueGreen: !Equals [!Ref DeploymentType, BlueGreen]

Resources:
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CodeBuildServiceRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeBuildDeveloperAccess
      Policies:
        - PolicyName: AdditionalPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                  - ecr:BatchGetImage
                  - ecr:PutImage
                  - s3:PutObject
                  - s3:GetObject
                Resource: "*"
        - PolicyName: GitHubConnectionAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - codestar-connections:GetConnectionToken
                  - codestar-connections:GetConnection
                  - codeconnections:GetConnectionToken
                  - codeconnections:GetConnection
                  - codeconnections:UseConnection
                Resource:
                  - !Ref GithubConnectionArn
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${AppName}-${Environment}-build"
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux-x86_64-standard:5.0
        Type: LINUX_CONTAINER
        PrivilegedMode: true  # Eğer Docker build yapıyorsan gerekli
        EnvironmentVariables:
          - Name: AWS_REGION
            Value: !Ref AWS::Region
            Type: PLAINTEXT

          - Name: ACCOUNT_ID
            Value: !Ref AWS::AccountId
            Type: PLAINTEXT

          - Name: APP_NAME
            Value: !Ref AppName
            Type: PLAINTEXT

          - Name: ENVIRONMENT
            Value: !Ref Environment
            Type: PLAINTEXT

          - Name: REPO_NAME
            Value: !Sub "${AppName}/${Environment}"
            Type: PLAINTEXT

          - Name: ECR_URI
            Value: !ImportValue ECRUri-Export
            Type: PLAINTEXT

          - Name: TASK_DEFINITION_ARN
            Value: !Sub "arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:task-definition/${AppName}-${Environment}:1"
            Type: PLAINTEXT

          - Name: TASK_DEFINITION_FAMILY
            Value: !Sub "${AppName}-${Environment}"
            Type: PLAINTEXT              

          - Name: TASK_EXECUTION_ROLE 
            Value: !Sub "arn:aws:iam::${AWS::AccountId}:role/${AppName}-${Environment}-task-execution-role"
            Type: PLAINTEXT
      
          - Name: CONTAINER_NAME
            Value: !Ref ContainerName
            Type: PLAINTEXT             

          - Name: CONTAINER_PORT
            Value: !Ref ContainerPort
            Type: PLAINTEXT

      Artifacts:
        Type: S3
        Location: !Ref ArtifactBucket
        Packaging: ZIP
      Source:
        Type: GITHUB
        Location: !Sub "https://github.com/${GitRepoId}"
        GitCloneDepth: 1
        GitSubmodulesConfig:
          FetchSubmodules: false
        ReportBuildStatus: true
        BuildSpec: !If
          - IsRolling
          - ecs/rolling-update/buildspec.yml
          - ecs/blue-green/buildspec.yml
      TimeoutInMinutes: 5
      Tags:
        - Key: Environment
          Value: !Ref Environment

Outputs:
  CodeBuildProjectNameExport:
    Description: CodeBuildProjectName ***
    Value: !Ref CodeBuildProject
    Export:
      Name: CodeBuildProjectName-Export
  CodeBuildProjectArnExport:
    Description: CodeBuildProjectArn ***
    Value: !GetAtt CodeBuildProject.Arn
    Export:
      Name: CodeBuildProjectArn-Export