AWSTemplateFormatVersion: '2010-09-09'
Description: CodeBuild project for ECS Pipeline

Parameters:
  AppName:
    Type: String
    Description: App name

  Environment:
    Type: String
    Description: Environment name

  DeploymentType:
    Type: String
    Description: Deployment tipi (bluegreen veya rolling)

  GitRepoId:
    Type: String
    Description: owner/repo biçiminde GitHub repo ID'si

  GithubConnectionArn:
    Type: String
    Description: Github Connection ARN

  ArtifactBucket:
    Type: String

  ContainerPort:
    Type: Number

Conditions:
  IsRolling: !Equals [!Ref DeploymentType, rolling]
  IsBlueGreen: !Equals [!Ref DeploymentType, bluegreen]

Resources:
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AppName}-${Environment}-codebuild-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeBuildDeveloperAccess
      Policies:
        - PolicyName: AdditionalPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                  - ecr:BatchGetImage
                  - ecr:PutImage
                  - s3:PutObject
                  - s3:GetObject
                Resource: "*"
        - PolicyName: GitHubConnectionAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - codestar-connections:GetConnectionToken
                  - codestar-connections:GetConnection
                  - codeconnections:GetConnectionToken
                  - codeconnections:GetConnection
                  - codeconnections:UseConnection
                Resource:
                  - !Ref GithubConnectionArn
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${AppName}-${Environment}-codebuild-project"
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux-x86_64-standard:5.0
        Type: LINUX_CONTAINER
        PrivilegedMode: true  # Eğer Docker build yapıyorsan gerekli
        EnvironmentVariables:
          - Name: AWS_REGION
            Value: !Ref AWS::Region
            Type: PLAINTEXT

          - Name: ACCOUNT_ID
            Value: !Ref AWS::AccountId
            Type: PLAINTEXT

          - Name: APP_NAME
            Value: !Ref AppName
            Type: PLAINTEXT

          - Name: ENVIRONMENT
            Value: !Ref Environment
            Type: PLAINTEXT

          - Name: REPO_NAME
            Value: !Sub "${AppName}/${Environment}"
            Type: PLAINTEXT

          - Name: ECR_URI
            Value: 
              Fn::ImportValue:
                Fn::Sub: ${AppName}-${Environment}-ecr-uri
            Type: PLAINTEXT

          - Name: TASK_DEFINITION_ARN
            Value:
              Fn::ImportValue:
                Fn::Sub: ${AppName}-${Environment}-task-definition-arn
            Type: PLAINTEXT

          - Name: TASK_DEFINITION_FAMILY
            Value: !Sub "${AppName}-${Environment}"
            Type: PLAINTEXT              

          - Name: TASK_EXECUTION_ROLE 
            Value:
              Fn::ImportValue:
                Fn::Sub: ${AppName}-${Environment}-ecs-task-executionrole-arn
            Type: PLAINTEXT
      
          - Name: CONTAINER_NAME
            Value: !Sub "${AppName}-${Environment}"
            Type: PLAINTEXT             

          - Name: CONTAINER_PORT
            Value: !Ref ContainerPort
            Type: PLAINTEXT

      Artifacts:
        Type: CODEPIPELINE 
        Packaging: ZIP
      Source:
        Type: CODEPIPELINE
        BuildSpec: !If
          - IsRolling
          - ecs/rolling-update/buildspec.yml
          - ecs/blue-green/buildspec.yml
      TimeoutInMinutes: 5
      Tags:
        - Key: Environment
          Value: !Ref Environment

Outputs:
  CodeBuildProjectArn:
    Description: CodeBuild Project Arn
    Value: !GetAtt CodeBuildProject.Arn
    Export:
      Name: !Sub ${AppName}-${Environment}-codebuild-project-arn