AWSTemplateFormatVersion: '2010-09-09'
Description: Parametrik ECS Task Definition Template

Parameters:
  AppName:
    Type: String
    Description: App name

  Environment:
    Type: String
    Description: Environment name

  ContainerPort:
    Type: Number

Resources:
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AppName}-${Environment}-task-execution-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: SSMParameterAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameters
                  - ssm:GetParameter
                Resource: 
                  - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AppName}/${Environment}/db/*"
              - Effect: Allow
                Action:
                  - kms:Decrypt
                Resource: "*"

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${AppName}-${Environment}"
      Cpu: "200"
      Memory: "150"
      NetworkMode: bridge
      RequiresCompatibilities:
        - EC2
      ExecutionRoleArn: !Ref TaskExecutionRole
      TaskRoleArn: !Ref TaskExecutionRole
      ContainerDefinitions:
        - Name: !Sub "${AppName}-${Environment}"
          Image: "public.ecr.aws/docker/library/nginx:stable"
          Cpu: 0
          Essential: true
          PortMappings:
            - ContainerPort: !Ref ContainerPort
              HostPort: !Ref ContainerPort
              Protocol: tcp
              Name: !Sub "${AppName}-${Environment}-${ContainerPort}-tcp"
              AppProtocol: http
          Secrets:
            - Name: DATABASE_HOST
              ValueFrom: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AppName}/${Environment}/db/host"
            - Name: DATABASE_HOST_PORT
              ValueFrom: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AppName}/${Environment}/db/port"
            - Name: DATABASE_USER
              ValueFrom: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AppName}/${Environment}/db/user"
            - Name: DATABASE_PASS
              ValueFrom: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AppName}/${Environment}/db/pass"
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub "/ecs/${AppName}-${Environment}"
              awslogs-create-group: "true"
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs

Outputs:
  TaskExecutionRoleExport:
    Description: TaskExecutionRole ***
    Value: !GetAtt TaskExecutionRole.Arn
    Export:
      Name: TaskExecutionRoleArn-Export

  TaskDefinitionExport:
    Description: TaskDefinition ***
    Value: !Ref TaskDefinition
    Export:
      Name: TaskDefinition-Export