AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Cluster Template

Parameters:
  AppName:
    Type: String
    Description: App name

  Environment:
    Type: String
    Description: Environment name

  InstanceType:
    Type: String
    Description: EC2 instance tipi

  KeyName:
    Type: String
    Description: Key-pair

  AmiId:
    Type: AWS::EC2::Image::Id
    Description: ECS-uyumlu AMI ID

  ContainerPort:
    Type: Number

Resources:

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${AppName}-${Environment}-cluster"
      ClusterSettings:
        - Name: containerInsights
          Value: enabled

  ContainerHostSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ECS container host security group
      VpcId:
        Fn::ImportValue:
          Fn::Sub: ${AppName}-${Environment}-VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref ContainerPort
          ToPort: !Ref ContainerPort
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "${AppName}-${Environment}-ecs-sg"

  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AppName}-${Environment}-ecs-ec2-role"
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Path: /

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref EC2Role

  ContainerInstances:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub "${AppName}-${Environment}-ecs-launch"
      LaunchTemplateData:
        ImageId: !Ref AmiId
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        IamInstanceProfile:
          Name: !Ref EC2InstanceProfile
        SecurityGroupIds:
          - !Ref ContainerHostSecurityGroup
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash -xe
            echo ECS_CLUSTER=${ECSCluster} >> /etc/ecs/ecs.config
            yum install -y aws-cfn-bootstrap
            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource ContainerInstances --configsets full_install --region ${AWS::Region}
        MetadataOptions:
          HttpEndpoint: enabled
          HttpTokens: required

  ECSAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    DependsOn:
      - ECSCluster
      - EC2Role
    Properties:
      VPCZoneIdentifier:
        - Fn::ImportValue:
            Fn::Sub: ${AppName}-${Environment}-PublicSubnet1Id
        - Fn::ImportValue:
            Fn::Sub: ${AppName}-${Environment}-PublicSubnet2Id
      LaunchTemplate:
        LaunchTemplateId: !Ref ContainerInstances
        Version: !GetAtt ContainerInstances.LatestVersionNumber
      MinSize: 1
      MaxSize: 2
      DesiredCapacity: 1
      NewInstancesProtectedFromScaleIn: false
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: true

  CapacityProvider:
    Type: AWS::ECS::CapacityProvider
    Properties:
      Name: !Sub "${AppName}-${Environment}-capacity-provider"
      AutoScalingGroupProvider:
        AutoScalingGroupArn: !Ref ECSAutoScalingGroup
        ManagedScaling:
          InstanceWarmupPeriod: 60
          MinimumScalingStepSize: 1
          MaximumScalingStepSize: 100
          Status: ENABLED
          TargetCapacity: 100
        ManagedTerminationProtection: DISABLED

  CapacityProviderAssociation:
    Type: AWS::ECS::ClusterCapacityProviderAssociations
    Properties:
      CapacityProviders:
        - !Ref CapacityProvider
      Cluster: !Ref ECSCluster
      DefaultCapacityProviderStrategy:
        - Base: 0
          CapacityProvider: !Ref CapacityProvider
          Weight: 1
Outputs:
  CapacityProvider:
    Description: The cluster capacity provider that the service should use
    Value: !Ref CapacityProvider
    Export:
      Name: !Sub ${AppName}-${Environment}-CapacityProvider
  ECSCluster:
    Description: ECS Cluster ***
    Value: !Ref ECSCluster
    Export:
      Name: !Sub ${AppName}-${Environment}-ECSCluster