Parameters:
  AppName:
    Type: String
    Description: App name

  Environment:
    Type: String
    Description: Environment name
    
Resources:
  CodeDeployRoleForECSBlueGreen:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AppName}-${Environment}-codedeploy-role-for-ecs-bluegreen
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codedeploy.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeDeployRoleForECS

  CodeDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: !Sub "${AppName}-${Environment}-codedeploy-app"
      ComputePlatform: ECS
  
  CodeDeployDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref CodeDeployApplication
      DeploymentGroupName: !Sub "${AppName}-${Environment}-dg"
      DeploymentConfigName: CodeDeployDefault.ECSAllAtOnce
      ServiceRoleArn: !GetAtt CodeDeployRoleForECSBlueGreen.Arn
      DeploymentStyle:
        DeploymentType: BLUE_GREEN
        DeploymentOption: WITH_TRAFFIC_CONTROL
      BlueGreenDeploymentConfiguration:
        TerminateBlueInstancesOnDeploymentSuccess:
          Action: TERMINATE
          TerminationWaitTimeInMinutes: 5
        DeploymentReadyOption:
          ActionOnTimeout: CONTINUE_DEPLOYMENT
          WaitTimeInMinutes: 0
      LoadBalancerInfo:
        TargetGroupPairInfoList:
          - TargetGroups:
            - Name: !Sub "${AppName}-blue-tg"
            - Name: !Sub "${AppName}-green-tg"

            ProdTrafficRoute:
              ListenerArns:
                - Fn::ImportValue:
                    Fn::Sub: ${AppName}-${Environment}-alb-listener-arn
            TestTrafficRoute:
              ListenerArns:
                - Fn::ImportValue:
                    Fn::Sub: ${AppName}-${Environment}-alb-test-listener-arn
      ECSServices:
        - ClusterName: !Sub "${AppName}-${Environment}-cluster"
          ServiceName: !Sub "${AppName}-${Environment}-service"
          
Outputs:
  CodeDeployAppArn:
    Description: "CodeDeploy Application ARN (manually constructed)"
    Value: !Sub arn:aws:codedeploy:${AWS::Region}:${AWS::AccountId}:application:${AppName}-${Environment}
    Export:
      Name: !Sub ${AppName}-${Environment}-codedeploy-app-arn

  CodeDeployDGArn:
    Description: "CodeDeploy Deployment Group ARN (manually constructed)"
    Value: !Sub
      - arn:aws:codedeploy:${AWS::Region}:${AWS::AccountId}:deploymentgroup:${AppName}-${Environment}/${DGName}
      - DGName: !Ref CodeDeployDeploymentGroup
    Export:
      Name: !Sub ${AppName}-${Environment}-codedeploy-dg-arn