AWSTemplateFormatVersion: '2010-09-09'
Description: CodePipeline IAM Role with Conditional IAM Policies for ECS Deployment

Parameters:
  AppName:
    Type: String
    Description: App name

  Environment:
    Type: String
    Description: Environment name

  ArtifactBucket:
    Type: String
    Description: S3 bucket name used by CodePipeline

  GithubConnectionArn:
    Type: String
    Description: Github Connection ARN

Resources:

  ### IAM Role
  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AppName}-${Environment}-codepipeline-servicerole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole

  ### Base Policy (Her iki durumda da geçerli)
  BasePolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${AppName}-${Environment}-codepipeline-base-policies
      Roles:
        - !Ref CodePipelineServiceRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowS3BucketAccess
            Effect: Allow
            Action:
              - s3:GetBucketVersioning
              - s3:GetBucketAcl
              - s3:GetBucketLocation
            Resource: !Sub arn:aws:s3:::${ArtifactBucket}
            Condition:
              StringEquals:
                aws:ResourceAccount: !Ref AWS::AccountId

          - Sid: AllowS3ObjectAccess
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:PutObjectAcl
              - s3:GetObject
              - s3:GetObjectVersion
            Resource: !Sub arn:aws:s3:::${ArtifactBucket}/*
            Condition:
              StringEquals:
                aws:ResourceAccount: !Ref AWS::AccountId

          - Effect: Allow
            Action:
              - codebuild:BatchGetBuilds
              - codebuild:StartBuild
              - codebuild:BatchGetBuildBatches
              - codebuild:StartBuildBatch
            Resource:
              Fn::ImportValue:
                Fn::Sub: ${AppName}-${Environment}-codebuild-project-arn
          - Effect: Allow
            Action:
              - codeconnections:UseConnection
              - codestar-connections:UseConnection
            Resource:
              - !Ref GithubConnectionArn

Outputs:
  CodePipelineServiceRoleName:
    Description: CodePipelineServiceRole Name
    Value: !Ref CodePipelineServiceRole
    Export:
      Name: !Sub ${AppName}-${Environment}-codepipeline-servicerole-name
  CodePipelineServiceRoleArn:
    Description: CodePipelineServiceRole Arn
    Value: !GetAtt CodePipelineServiceRole.Arn
    Export:
      Name: !Sub ${AppName}-${Environment}-codepipeline-servicerole-arn