AWSTemplateFormatVersion: '2010-09-09'
Description: CodePipeline IAM Role with Conditional IAM Policies for ECS Deployment

Parameters:
  AppName:
    Type: String
    Description: App name

  Environment:
    Type: String
    Description: Environment name

  DeploymentType:
    Type: String
    Description: Deployment Type (Rolling or BlueGreen)

  ArtifactBucket:
    Type: String
    Description: S3 bucket name used by CodePipeline

  GithubConnectionArn:
    Type: String
    Description: Github Connection ARN

  CodeDeployApplication:
    Type: String
    Description: ARN of the CodeDeploy Application (Only required for BlueGreen)
    Default: ""

  CodeDeployDeploymentGroup:
    Type: String
    Description: ARN of the CodeDeploy DeploymentGroup (Only required for BlueGreen)
    Default: ""

Conditions:
  IsRolling: !Equals [!Ref DeploymentType, "Rolling"]
  IsBlueGreen: !Equals [!Ref DeploymentType, "BlueGreen"]

Resources:

  ### IAM Role
  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CodePipelineServiceRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole

  ### Base Policy (Her iki durumda da geçerli)
  BasePolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: BaseCodePipelinePolicies
      Roles:
        - !Ref CodePipelineServiceRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowS3BucketAccess
            Effect: Allow
            Action:
              - s3:GetBucketVersioning
              - s3:GetBucketAcl
              - s3:GetBucketLocation
            Resource: !Sub arn:aws:s3:::${ArtifactBucket}
            Condition:
              StringEquals:
                aws:ResourceAccount: !Ref AWS::AccountId

          - Sid: AllowS3ObjectAccess
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:PutObjectAcl
              - s3:GetObject
              - s3:GetObjectVersion
            Resource: !Sub arn:aws:s3:::${ArtifactBucket}/*
            Condition:
              StringEquals:
                aws:ResourceAccount: !Ref AWS::AccountId

          - Effect: Allow
            Action:
              - codebuild:BatchGetBuilds
              - codebuild:StartBuild
              - codebuild:BatchGetBuildBatches
              - codebuild:StartBuildBatch
            Resource: !ImportValue CodeBuildProjectArn-Export

          - Effect: Allow
            Action:
              - codeconnections:UseConnection
              - codestar-connections:UseConnection
            Resource:
              - !Ref GithubConnectionArn
  ### Rolling Policy
  RollingEcsPolicy:
    Type: AWS::IAM::Policy
    Condition: IsRolling
    Properties:
      PolicyName: RollingECSAccess
      Roles:
        - !Ref CodePipelineServiceRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: TaskDefinitionPermissions
            Effect: Allow
            Action:
              - ecs:DescribeTaskDefinition
              - ecs:RegisterTaskDefinition
            Resource: "*"

          - Sid: ECSServicePermissions
            Effect: Allow
            Action:
              - ecs:DescribeServices
              - ecs:UpdateService
            Resource:
              - !ImportValue ECSServiceArn-Export

          - Sid: ECSTaskDefinitionRegistration
            Effect: Allow
            Action:
              - ecs:RegisterTaskDefinition
              - ecs:TagResource
            Resource: "*"
            Condition:
              StringEquals:
                ecs:CreateAction:
                  - RegisterTaskDefinition

          - Sid: IamPassRolePermissions
            Effect: Allow
            Action: iam:PassRole
            Resource:
              - !ImportValue TaskExecutionRoleArn-Export
            Condition:
              StringEquals:
                iam:PassedToService:
                  - ecs.amazonaws.com
                  - ecs-tasks.amazonaws.com

  ### BlueGreen Policy
  BlueGreenPolicy:
    Type: AWS::IAM::Policy
    Condition: IsBlueGreen
    Properties:
      PolicyName: CodeDeployAndECSAccess
      Roles:
        - !Ref CodePipelineServiceRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCodeDeployDeploymentActions
            Effect: Allow
            Action:
              - codedeploy:CreateDeployment
              - codedeploy:GetDeployment
            Resource: !ImportValue CodeDeployDeploymentGroupArn-Export

          - Sid: AllowCodeDeployApplicationActions
            Effect: Allow
            Action:
              - codedeploy:GetApplication
              - codedeploy:GetApplicationRevision
              - codedeploy:RegisterApplicationRevision
            Resource:
              - !ImportValue CodeDeployApplicationArn-Export
              - !Sub
                  - "${AppArn}/*"
                  - AppArn: !ImportValue CodeDeployApplicationArn-Export

          - Sid: AllowCodeDeployDeploymentConfigAccess
            Effect: Allow
            Action:
              - codedeploy:GetDeploymentConfig
            Resource: "*"

          - Sid: AllowECSRegisterTaskDefinition
            Effect: Allow
            Action:
              - ecs:RegisterTaskDefinition
            Resource: "*"

          - Sid: AllowPassRoleToECS
            Effect: Allow
            Action: iam:PassRole
            Resource: !ImportValue TaskExecutionRoleArn-Export
            Condition:
              StringEquals:
                iam:PassedToService:
                  - ecs.amazonaws.com
                  - ecs-tasks.amazonaws.com

Outputs:
  CodePipelineServiceRoleExport:
    Description: CodePipelineServiceRole ***
    Value: !GetAtt CodePipelineServiceRole.Arn
    Export:
      Name: CodePipelineServiceRoleArn-Export