AWSTemplateFormatVersion: '2010-09-09'
Description: CodePipeline for Sample App Web Build

Parameters:
  AppName:
    Type: String
    Description: App name

  Environment:
    Type: String
    Description: Environment name

  DeploymentType:
    Type: String
    Description: Deployment Type (Rolling or BlueGreen)

  GithubConnectionArn:
    Type: String
    Description: Github Connection ARN

  GitRepoId:
    Type: String
    Description: owner/repo biçiminde GitHub repo ID'si

  GitBranch:
    Type: String
    Default: main

  ArtifactBucket:
    Type: String
    Description: S3 bucket name used by CodePipeline

  ContainerPort:
    Type: Number

Conditions:
  IsRolling: !Equals [ !Ref DeploymentType, "Rolling" ]
  IsBlueGreen: !Equals [ !Ref DeploymentType, "BlueGreen" ]

Resources:

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub "${AppName}-${Environment}-${DeploymentType}-Pipeline"
      RoleArn: !ImportValue CodePipelineServiceRoleArn-Export
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              Configuration:
                ConnectionArn: !Ref GithubConnectionArn
                FullRepositoryId: !Ref GitRepoId
                BranchName: !Ref GitBranch
                DetectChanges: 'true'
                OutputArtifactFormat: CODE_ZIP
              OutputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !ImportValue CodeBuildProjectName-Export
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
              RunOrder: 1
        - Name: Deploy
          Actions:
            #Rolling Update
            - !If
              - IsRolling
              - Name: Deploy
                ActionTypeId:
                  Category: Deploy
                  Owner: AWS
                  Provider: ECS
                  Version: '1'
                Configuration:
                  ClusterName: !ImportValue ECSCluster-Export
                  ServiceName: !ImportValue ECSService-Export
                InputArtifacts:
                  - Name: BuildArtifact
                RunOrder: 1
              - !Ref "AWS::NoValue"
            #Blue/Green Deployment
            - !If
              - IsBlueGreen
              - Name: Deploy
                ActionTypeId:
                  Category: Deploy
                  Owner: AWS
                  Provider: CodeDeployToECS
                  Version: '1'
                Configuration:
                  ApplicationName: !ImportValue CodeDeployApplicationName-Export
                  DeploymentGroupName: !ImportValue CodeDeployDeploymentGroupName-Export
                  AppSpecTemplateArtifact: BuildArtifact
                  TaskDefinitionTemplateArtifact: BuildArtifact
                  Image1ArtifactName: BuildArtifact
                  Image1ContainerName: !Sub "${AppName}-${Environment}"
                InputArtifacts:
                  - Name: BuildArtifact
                RunOrder: 1
              - !Ref "AWS::NoValue"
      PipelineType: V2
      Triggers:
        - ProviderType: CodeStarSourceConnection
          GitConfiguration:
            SourceActionName: Source
            Push:
              - Branches:
                  Includes:
                    - !Ref GitBranch