Parameters:
  AppName:
    Type: String
    Description: App name
    Default: ledger-app

  Environment:
    Type: String
    Description: Environment name
    AllowedValues:
      - prod
      - dev
    Default: prod

Resources:
AssetsBucket:
  Type: AWS::S3::Bucket
  BucketName: !Sub "${AppName}-${Environment}-${AWS::AccountId}-assets"
  DeletionPolicy: Retain
  UpdateReplacePolicy: Retain

ArtifactsBucket:
  Type: AWS::S3::Bucket
  BucketName: !Sub "${AppName}-${Environment}-${AWS::AccountId}-artifacts"
  DeletionPolicy: Retain
  UpdateReplacePolicy: Retain

Outputs:
  AssetsBucketName:
    Value: !Ref AssetsBucket
    Export:
      Name: !Sub "${AppName}-${Environment}-assets-bucket"

  ArtifactsBucketName:
    Value: !Ref AssetArtifactsBucketsBucket
    Export:
      Name: !Sub "${AppName}-${Environment}-asartifactssets-bucket"