# main-stack.yaml
Parameters:
  AppName:
    Type: String
    Description: App name
    Default: ledger-app

  Environment:
    Type: String
    Description: Environment name
    AllowedValues:
      - prod
      - dev
    Default: prod

  DeploymentType:
    Type: String
    Description: Deployment tipi (bluegreen veya rolling)
    AllowedValues:
      - bluegreen
      - rolling
    Default: rolling

  GithubConnectionArn:
    Type: String
    Description: Github Connection ARN
    Default: arn:aws:codeconnections:eu-north-1:253712034003:connection/2c02ecd9-b115-4cec-967f-a0e4445ecfaa

  SourceRepo:
    Type: String
    Description: owner/repo biçiminde GitHub repo ID'si
    Default: zbalci/ledger-app-aws-ecs

  SourceBranch:
    Type: String
    Default: main

  InstanceType:
    Type: String
    Description: EC2 instance tipi
    Default: t3.micro

  KeyName:
    Type: String
    Default: zekib
    Description: Key-pair

  AmiId:
    Type: AWS::EC2::Image::Id
    Description: ECS-uyumlu AMI ID
    Default: ami-0f3092a09bb5324c4

  ContainerPort:
    Type: Number
    Default: 80

  ListenerPort:
    Type: Number
    Default: 80

  TestListenerPort:
    Type: Number
    Default: 8080

  ArtifactBucket:
    Type: String
    Description: S3 bucket name used by CodePipeline
    Default: ledger-app-artifacts-bucket

Conditions:
  IsRolling: !Equals [ !Ref DeploymentType, "rolling" ]
  IsBlueGreen: !Equals [ !Ref DeploymentType, "bluegreen" ]

Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://ledger-app-aws-iac.s3.eu-north-1.amazonaws.com/network/vpc.yaml
      Parameters:
        AppName: !Ref AppName
        Environment: !Ref Environment

  AlbStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VpcStack
    Properties:
      TemplateURL: https://ledger-app-aws-iac.s3.eu-north-1.amazonaws.com/loadbalancing/alb.yaml
      Parameters:
        AppName: !Ref AppName
        Environment: !Ref Environment
        DeploymentType: !Ref DeploymentType
        ContainerPort: !Ref ContainerPort
        ListenerPort: !Ref ListenerPort
        TestListenerPort: !Ref TestListenerPort

  EcrStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://ledger-app-aws-iac.s3.eu-north-1.amazonaws.com/registry/ecr.yaml
      Parameters:
        AppName: !Ref AppName
        Environment: !Ref Environment

  EcsTaskDefStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://ledger-app-aws-iac.s3.eu-north-1.amazonaws.com/ecs/taskdefinition.yaml
      Parameters:
        AppName: !Ref AppName
        Environment: !Ref Environment
        ContainerPort: !Ref ContainerPort

  EcsClusterStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VpcStack
    Properties:
      TemplateURL: https://ledger-app-aws-iac.s3.eu-north-1.amazonaws.com/ecs/cluster.yaml
      Parameters:
        AppName: !Ref AppName
        Environment: !Ref Environment
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        AmiId: !Ref AmiId
        ContainerPort: !Ref ContainerPort

  EcsServiceStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - EcsClusterStack
      - AlbStack
    Properties:
      TemplateURL: https://ledger-app-aws-iac.s3.eu-north-1.amazonaws.com/ecs/service.yaml
      Parameters:
        AppName: !Ref AppName
        Environment: !Ref Environment
        DeploymentType: !Ref DeploymentType
        ContainerPort: !Ref ContainerPort

  CodePipelineStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - AlbStack
      - EcsServiceStack
    Properties:
      TemplateURL: https://ledger-app-aws-iac.s3.eu-north-1.amazonaws.com/pipeline/root.yaml
      Parameters:
        AppName: !Ref AppName
        Environment: !Ref Environment
        DeploymentType: !Ref DeploymentType
        SourceRepo: !Ref SourceRepo
        SourceBranch: !Ref SourceBranch
        ArtifactBucket: !Ref ArtifactBucket
        GithubConnectionArn: !Ref GithubConnectionArn
        ContainerPort: !Ref ContainerPort