AWSTemplateFormatVersion: '2010-09-09'
Description: CodeBuild project for Lambda Pipeline

Parameters:
  AppName:
    Type: String
    Description: App name

  Environment:
    Type: String
    Description: Environment name

  GithubConnectionArn:
    Type: String
    Description: Github Connection ARN

  SourceRepo:
    Type: String
    Description: owner/repo biçiminde GitHub repo ID'si

  SourceBranch:
    Type: String

Resources:
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AppName}-${Environment}-db-init-build-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeBuildDeveloperAccess
      Policies:
        - PolicyName: AdditionalPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: AllowLogging
                Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/${AppName}-${Environment}/codebuild:*"

              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: "*" # Auth token (zorunlu *)

              - Sid: AllowECRAccess
                Effect: Allow
                Action:
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                  - ecr:BatchGetImage
                  - ecr:PutImage
                Resource: !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/${AppName}-${Environment}*"


              - Sid: AllowECSTaskAccess
                Effect: Allow
                Action:
                  - ecs:RunTask
                  - ecs:DescribeTasks
                Resource: "*"

              - Sid: AllowS3Access
                Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource:
                  - !Sub
                      - "arn:aws:s3:::${ArtifactBucket}/*"
                      - ArtifactBucket:
                          Fn::ImportValue: !Sub "${AppName}-${Environment}-artifact-bucket-name"
                  - !Sub
                      - "arn:aws:s3:::${AssetBucket}/*"
                      - AssetBucket:
                          Fn::ImportValue: !Sub "${AppName}-${Environment}-asset-bucket-name"

              - Sid: AllowSecretManagerAccess
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !ImportValue
                  Fn::Sub: ${AppName}-${Environment}-rds-master-secret-arn
              - Effect: Allow
                Action:
                  - kms:Decrypt
                Resource: '*'
    
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource:
                  Fn::ImportValue:
                     Fn::Sub: ${AppName}-${Environment}-db-init-ecs-task-executionrole-arn
   
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${AppName}-${Environment}-db-init-build-project"
      ServiceRole: !GetAtt CodeBuildRole.Arn
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
          GroupName: !Sub "/${AppName}-${Environment}/codebuild"
          StreamName: "db-init"
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
        PrivilegedMode: true  # Eğer Docker build yapıyorsan gerekli
        EnvironmentVariables:
          - Name: AWS_REGION
            Value: !Ref AWS::Region
            Type: PLAINTEXT
          - Name: ACCOUNT_ID
            Value: !Ref AWS::AccountId
            Type: PLAINTEXT
          - Name: REPO_NAME
            Value: !Sub "${AppName}-${Environment}-db-init"
            Type: PLAINTEXT
          - Name: ASSET_BUCKET
            Value:
              Fn::ImportValue:
                Fn::Sub: "${AppName}-${Environment}-asset-bucket-name"
            Type: PLAINTEXT
          - Name: ECR_URI
            Value: 
              Fn::ImportValue:
                Fn::Sub: ${AppName}-${Environment}-db-init-ecr-uri
            Type: PLAINTEXT
          - Name: ECS_CLUSTER
            Value: !Sub "${AppName}-${Environment}-ecs-cluster"
          - Name: TASK_DEFINITION
            Value: !Sub ${AppName}-${Environment}-db-init
      Artifacts:
        Type: CODEPIPELINE 
      Source:
        Type: CODEPIPELINE
        BuildSpec: infrastructure/cicd/db-init/buildspec.yml
      TimeoutInMinutes: 5

  ### IAM Role for CodePipeline
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AppName}-${Environment}-db-init-pipeline-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole

  CodePipelinePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${AppName}-${Environment}-db-init-pipeline-policy
      Roles:
        - !Ref CodePipelineRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowS3BucketAccess
            Effect: Allow
            Action:
              - s3:GetBucketVersioning
              - s3:GetBucketAcl
              - s3:GetBucketLocation
            Resource:
              !Sub
                - "arn:aws:s3:::${BucketName}/*"
                - BucketName:
                    Fn::ImportValue: !Sub "${AppName}-${Environment}-artifact-bucket-name"
            Condition:
              StringEquals:
                aws:ResourceAccount: !Ref AWS::AccountId

          - Sid: AllowS3ObjectAccess
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:PutObjectAcl
              - s3:GetObject
              - s3:GetObjectVersion
            Resource:
              !Sub
                - "arn:aws:s3:::${BucketName}/*"
                - BucketName:
                    Fn::ImportValue: !Sub "${AppName}-${Environment}-artifact-bucket-name"
            Condition:
              StringEquals:
                aws:ResourceAccount: !Ref AWS::AccountId

          - Effect: Allow
            Action:
              - codebuild:BatchGetBuilds
              - codebuild:StartBuild
            Resource: !GetAtt CodeBuildProject.Arn

          - Sid: GitHubConnectionAccess
            Effect: Allow
            Action:
              - codestar-connections:UseConnection
            Resource:
              - !Ref GithubConnectionArn

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    DependsOn: 
      - CodePipelinePolicy
    Properties:
      Name: !Sub "${AppName}-${Environment}-db-init-pipeline"
      RoleArn: !GetAtt CodePipelineRole.Arn

      ArtifactStore:
        Type: S3
        Location: 
          Fn::ImportValue: !Sub "${AppName}-${Environment}-artifact-bucket-name"

      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              Configuration:
                ConnectionArn: !Ref GithubConnectionArn
                FullRepositoryId: !Ref SourceRepo
                BranchName: !Ref SourceBranch
                DetectChanges: true
              OutputArtifacts:
                - Name: SourceArtifact

        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref CodeBuildProject
              InputArtifacts:
                - Name: SourceArtifact