Parameters:
  AppName:
    Type: String
    Description: App name

  Environment:
    Type: String
    Description: Environment name

  GithubConnectionArn:
    Type: String
    Description: Github Connection ARN

  SourceRepo:
    Type: String
    Description: owner/repo biçiminde GitHub repo ID'si
    
  SourceBranch:
    Type: String

Resources:
  DBInitECRStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://ledger-app-aws-iac.s3.eu-north-1.amazonaws.com/registry/db-init/repository.yaml
      Parameters:
        AppName: !Ref AppName
        Environment: !Ref Environment

  DBInitTaskDefStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - DBInitECRStack
    Properties:
      TemplateURL: https://ledger-app-aws-iac.s3.eu-north-1.amazonaws.com/pipeline/db-init/task-definition.yaml
      Parameters:
        AppName: !Ref AppName
        Environment: !Ref Environment

  DBInitPipelineStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - DBInitTaskDefStack
    Properties:
      TemplateURL: https://ledger-app-aws-iac.s3.eu-north-1.amazonaws.com/pipeline/db-init/pipeline.yaml
      Parameters:
        AppName: !Ref AppName
        Environment: !Ref Environment
        GithubConnectionArn: !Ref GithubConnectionArn
        SourceRepo: !Ref SourceRepo
        SourceBranch: !Ref SourceBranch
