Description: Parametrik ECS Task Definition Template

Parameters:
  AppName:
    Type: String
    Description: App name
  Environment:
    Type: String
    Description: Environment name

Resources:
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AppName}-${Environment}-db-init-task-execution-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: SSMParameterAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameters
                  - ssm:GetParameter
                Resource:
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AppName}/${Environment}/db/*
 
              - Sid: AllowSecretManagerAccess
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !ImportValue
                  Fn::Sub: ${AppName}-${Environment}-rds-master-secret-arn

              - Effect: Allow
                Action:
                  - kms:Decrypt
                Resource: '*'

        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - !Sub
                      - "arn:aws:s3:::${BucketName}/*"
                      - BucketName:
                          Fn::ImportValue: !Sub "${AppName}-${Environment}-asset-bucket-name"
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${AppName}-${Environment}-db-init
      Cpu: '200'
      Memory: '150'
      NetworkMode: bridge
      RequiresCompatibilities:
        - EC2
      ExecutionRoleArn: !Ref TaskExecutionRole
      TaskRoleArn: !Ref TaskExecutionRole
      ContainerDefinitions:
        - Name: !Sub ${AppName}-${Environment}-db-init
          Image: 
            Fn::ImportValue: !Sub ${AppName}-${Environment}-db-init-ecr-uri
          Command:
            - |
              set -e

              echo "==== DB INIT START ===="

              echo "Downloading SQL file from S3..."
              aws s3 cp s3://$ASSET_BUCKET/database/init.sql /tmp/init.sql
              echo "SQL file downloaded"

              echo "Waiting for database to be reachable..."
              until mysql -h "$DATABASE_HOST" -u "$DATABASE_USER" -p"$DATABASE_PASS" -e "select 1"; do
                echo "DB not ready yet..."
                sleep 5
              done

              echo "DB is reachable"

              echo "Running SQL file..."
              mysql -h "$DATABASE_HOST" \
                    -u "$DATABASE_USER" \
                    -p"$DATABASE_PASS" \
                    "$DATABASE" < /tmp/init.sql

              echo "SQL execution finished"

              echo "Listing tables:"
              mysql -h "$DATABASE_HOST" \
                    -u "$DATABASE_USER" \
                    -p"$DATABASE_PASS" \
                    "$DATABASE" \
                    -e "SHOW TABLES;"

              echo "==== DB INIT END ===="

          Cpu: 0
          Essential: true
          Environment:
            - Name: ASSET_BUCKET
              Value:
                Fn::ImportValue:
                  Fn::Sub: "${AppName}-${Environment}-asset-bucket-name"
          Secrets:
            - Name: DATABASE
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AppName}/${Environment}/db/database
            - Name: DATABASE_HOST
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AppName}/${Environment}/db/host
            - Name: DATABASE_HOST_PORT
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AppName}/${Environment}/db/port
            - Name: DATABASE_USER
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AppName}/${Environment}/db/user
            - Name: DATABASE_PASS
              ValueFrom: !Sub
                - '${SecretArn}:password::'
                - SecretArn: !ImportValue
                    Fn::Sub: ${AppName}-${Environment}-rds-master-secret-arn
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub /${AppName}-${Environment}/ecs
              awslogs-create-group: 'true'
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: db-init

Outputs:
  TaskExecutionRole:
    Description: TaskExecutionRole Arn
    Value: !GetAtt TaskExecutionRole.Arn
    Export:
      Name: !Sub ${AppName}-${Environment}-db-init-ecs-task-executionrole-arn