# main-stack.yaml
Parameters:
  AppName:
    Type: String
    Description: App name
    Default: ledger-app

  Environment:
    Type: String
    Description: Environment name
    AllowedValues:
      - prod
      - dev
    Default: prod

  DeploymentType:
    Type: String
    Description: Deployment tipi (bluegreen veya rolling)
    AllowedValues:
      - bluegreen
      - rolling
    Default: bluegreen

  GithubConnectionArn:
    Type: String
    Description: Github Connection ARN
    Default: arn:aws:codeconnections:eu-north-1:253712034003:connection/2c02ecd9-b115-4cec-967f-a0e4445ecfaa

  SourceRepo:
    Type: String
    Description: owner/repo biçiminde GitHub repo ID'si
    Default: zbalci/ledger-app-aws-ecs

  SourceBranch:
    Type: String
    Default: main

  ContainerPort:
    Type: Number
    Default: 80

  ListenerPort:
    Type: Number
    Default: 80

  TestListenerPort:
    Type: Number
    Default: 8080

Resources:
  # NetworkStack:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: https://ledger-app-aws-iac.s3.eu-north-1.amazonaws.com/network/vpc.yaml
  #     Tags:
  #       - Key: Application
  #         Value: !Ref AppName
  #       - Key: Environment
  #         Value: !Ref Environment
  #       - Key: ManagedBy
  #         Value: CloudFormation
  #     Parameters:
  #       AppName: !Ref AppName
  #       Environment: !Ref Environment

  # LoadbalanceStack:
  #   Type: AWS::CloudFormation::Stack
  #   DependsOn:
  #     - NetworkStack
  #   Properties:
  #     TemplateURL: https://ledger-app-aws-iac.s3.eu-north-1.amazonaws.com/loadbalance/alb.yaml
  #     Tags:
  #       - Key: Application
  #         Value: !Ref AppName
  #       - Key: Environment
  #         Value: !Ref Environment
  #       - Key: ManagedBy
  #         Value: CloudFormation
  #     Parameters:
  #       AppName: !Ref AppName
  #       Environment: !Ref Environment
  #       DeploymentType: !Ref DeploymentType
  #       ContainerPort: !Ref ContainerPort
  #       ListenerPort: !Ref ListenerPort
  #       TestListenerPort: !Ref TestListenerPort

  RegistryStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://ledger-app-aws-iac.s3.eu-north-1.amazonaws.com/registry/ecr.yaml
      Tags:
        - Key: Application
          Value: !Ref AppName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation
      Parameters:
        AppName: !Ref AppName
        Environment: !Ref Environment

  # DatabaseStack:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: https://ledger-app-aws-iac.s3.eu-north-1.amazonaws.com/database/root.yaml
  #     Tags:
  #       - Key: Application
  #         Value: !Ref AppName
  #       - Key: Environment
  #         Value: !Ref Environment
  #       - Key: ManagedBy
  #         Value: CloudFormation
  #     Parameters:
  #       AppName: !Ref AppName
  #       Environment: !Ref Environment
  #       GithubConnectionArn: !Ref GithubConnectionArn
  #       SourceRepo: !Ref SourceRepo
  #       SourceBranch: !Ref SourceBranch

  # EcsStack:
  #   Type: AWS::CloudFormation::Stack
  #   DependsOn:
  #     - NetworkStack
  #     - LoadbalanceStack
  #     - RegistryStack
  #     - DatabaseStack
  #   Properties:
  #     TemplateURL: https://ledger-app-aws-iac.s3.eu-north-1.amazonaws.com/ecs/root.yaml
  #     Tags:
  #       - Key: Application
  #         Value: !Ref AppName
  #       - Key: Environment
  #         Value: !Ref Environment
  #       - Key: ManagedBy
  #         Value: CloudFormation
  #     Parameters:
  #       AppName: !Ref AppName
  #       Environment: !Ref Environment
  #       DeploymentType: !Ref DeploymentType
  #       ContainerPort: !Ref ContainerPort

  # CodePipelineStack:
  #   Type: AWS::CloudFormation::Stack
  #   DependsOn:
  #     - NetworkStack
  #     - LoadbalanceStack
  #     - RegistryStack
  #     - DatabaseStack
  #     - EcsStack
  #   Properties:
  #     TemplateURL: https://ledger-app-aws-iac.s3.eu-north-1.amazonaws.com/pipeline/root.yaml
  #     Tags:
  #       - Key: Application
  #         Value: !Ref AppName
  #       - Key: Environment
  #         Value: !Ref Environment
  #       - Key: ManagedBy
  #         Value: CloudFormation
  #     Parameters:
  #       AppName: !Ref AppName
  #       Environment: !Ref Environment
  #       DeploymentType: !Ref DeploymentType
  #       SourceRepo: !Ref SourceRepo
  #       SourceBranch: !Ref SourceBranch
  #       GithubConnectionArn: !Ref GithubConnectionArn
  #       ContainerPort: !Ref ContainerPort