Parameters:
  AppName:
    Type: String
    Description: App name

  Environment:
    Type: String
    Description: Environment name

  AppPort:
    Type: Number

  TestPort:
    Type: Number

  DBPort:
    Type: Number
    Description: Database port

Resources:
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow public HTTP inbound, restricted outbound to ECS
      GroupName: !Sub "${AppName}-${Environment}-alb-sg"
      VpcId:
        Fn::ImportValue:
          Fn::Sub: ${AppName}-${Environment}-vpc-id

      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref AppPort
          ToPort: !Ref AppPort
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: !Ref TestPort
          ToPort: !Ref TestPort
          CidrIp: 0.0.0.0/0

      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  ContainerHostSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ECS service security group
      GroupName: !Sub "${AppName}-${Environment}-ecs-sg"
      VpcId:
        Fn::ImportValue:
          Fn::Sub: ${AppName}-${Environment}-vpc-id

      SecurityGroupIngress:
        # Only ALB can reach the service
        - IpProtocol: tcp
          FromPort: !Ref AppPort
          ToPort: !Ref AppPort
          SourceSecurityGroupId: !GetAtt ALBSecurityGroup.GroupId

      SecurityGroupEgress:
        # HTTPS for AWS APIs (Secrets Manager, SSM, ECR, CloudWatch)
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

        # Database access
        - IpProtocol: tcp
          FromPort: !Ref DBPort
          ToPort: !Ref DBPort
          CidrIp: 10.0.0.0/16   # or DB subnet CIDR

        # DNS resolution (required by ECS)
        - IpProtocol: udp
          FromPort: 53
          ToPort: 53
          CidrIp: 10.0.0.0/16

        - IpProtocol: tcp
          FromPort: 53
          ToPort: 53
          CidrIp: 10.0.0.0/16

  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: RDS access only from ECS, no outbound
      GroupName: !Sub "${AppName}-${Environment}-rds-sg"
      VpcId:
        Fn::ImportValue:
          Fn::Sub: ${AppName}-${Environment}-vpc-id

      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref DBPort
          ToPort: !Ref DBPort
          SourceSecurityGroupId: !GetAtt ContainerHostSecurityGroup.GroupId

      # No outbound traffic required for RDS
      SecurityGroupEgress: []

Outputs:
  ALBSecurityGroupId:
    Description: ALB Security Group Id
    Value: !GetAtt ALBSecurityGroup.GroupId
    Export:
      Name: !Sub ${AppName}-${Environment}-alb-sg-id

  ContainerHostSecurityGroupId:
    Description: Container Host Security Group Id
    Value: !GetAtt ContainerHostSecurityGroup.GroupId
    Export:
      Name: !Sub "${AppName}-${Environment}-ecs-sg-id"

  RDSSecurityGroupId:
    Description: RDS Security Group Id
    Value: !GetAtt RDSSecurityGroup.GroupId
    Export:
      Name: !Sub "${AppName}-${Environment}-rds-sg-id"