Parameters:
  AppName:
    Type: String
    Default: ledger-app

  Environment:
    Type: String
    AllowedValues:
      - prod
      - dev
    Default: prod

Resources:
  DbInitLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/${AppName}-${Environment}/lambda-db-init"
      RetentionInDays: 7

  CodeBuildLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/${AppName}-${Environment}/codebuild"
      RetentionInDays: 7

  EcsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/${AppName}-${Environment}/ecs"
      RetentionInDays: 7

  AssetBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub "${AppName}-${Environment}-${AWS::AccountId}-assets"

  ArtifactBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub "${AppName}-${Environment}-${AWS::AccountId}-artifacts"

Outputs:
  AssetBucketName:
    Value: !Ref AssetBucket
    Export:
      Name: !Sub "${AppName}-${Environment}-asset-bucket-name"

  ArtifactBucketName:
    Value: !Ref ArtifactBucket
    Export:
      Name: !Sub "${AppName}-${Environment}-artifact-bucket-name"