Parameters:
  AppName:
    Type: String
    Default: ledger

  Environment:
    Type: String
    AllowedValues:
      - prod
      - dev
    Default: dev

Resources:
  DbInitLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/${AppName}-${Environment}/lambda-db-init"
      RetentionInDays: 7
      Tags:
        - Key: Application
          Value: !Ref AppName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  CodeBuildLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/${AppName}-${Environment}/codebuild"
      RetentionInDays: 7
      Tags:
        - Key: Application
          Value: !Ref AppName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  EcsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/${AppName}-${Environment}/ecs"
      RetentionInDays: 7
      Tags:
        - Key: Application
          Value: !Ref AppName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  AssetBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub "${AppName}-${Environment}-${AWS::AccountId}-assets"
      Tags:
        - Key: Application
          Value: !Ref AppName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  AssetBucketS3Param:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AppName}/${Environment}/asset_bucket_s3"
      Type: String
      Value: !Sub "s3://${AssetBucket}"

  ArtifactBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub "${AppName}-${Environment}-${AWS::AccountId}-artifacts"
      Tags:
        - Key: Application
          Value: !Ref AppName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  ArtifactBucketS3Param:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AppName}/${Environment}/artifact_bucket_s3"
      Type: String
      Value: !Sub "s3://${ArtifactBucket}"

  IaCBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub "${AppName}-${Environment}-${AWS::AccountId}-iac"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
        IgnorePublicAcls: true
      Tags:
        - Key: Application
          Value: !Ref AppName
        - Key: ManagedBy
          Value: CloudFormation

  IaCBucketURLParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AppName}/${Environment}/iac_bucket_url"
      Type: String
      Value: !Sub "https://${IaCBucket}.s3.${AWS::Region}.amazonaws.com"

  IaCBucketS3Param:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AppName}/${Environment}/iac_bucket_s3"
      Type: String
      Value: !Sub "s3://${IaCBucket}"

Outputs:
  AssetBucketName:
    Value: !Ref AssetBucket
    Export:
      Name: !Sub "${AppName}-${Environment}-asset-bucket-name"

  ArtifactBucketName:
    Value: !Ref ArtifactBucket
    Export:
      Name: !Sub "${AppName}-${Environment}-artifact-bucket-name"