Parameters:
  AppName:
    Type: String
    Default: ledger

  Environment:
    Type: String
    AllowedValues:
      - prod
      - staging
      - dev
    Default: prod

Resources:
  DbInitLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/${AppName}-${Environment}/lambda-db-init"
      RetentionInDays: 7
      Tags:
        - Key: Application
          Value: !Ref AppName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  CodeBuildLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/${AppName}-${Environment}/codebuild"
      RetentionInDays: 7
      Tags:
        - Key: Application
          Value: !Ref AppName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  EcsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/${AppName}-${Environment}/ecs"
      RetentionInDays: 7
      Tags:
        - Key: Application
          Value: !Ref AppName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  AssetBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub "${AppName}-${Environment}-${AWS::AccountId}-assets"
      Tags:
        - Key: Application
          Value: !Ref AppName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  ArtifactBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub "${AppName}-${Environment}-${AWS::AccountId}-artifacts"
      Tags:
        - Key: Application
          Value: !Ref AppName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

Outputs:
  AssetBucketName:
    Value: !Ref AssetBucket
    Export:
      Name: !Sub "${AppName}-${Environment}-asset-bucket-name"

  ArtifactBucketName:
    Value: !Ref ArtifactBucket
    Export:
      Name: !Sub "${AppName}-${Environment}-artifact-bucket-name"