Parameters:
  AppName:
    Type: String
    Description: App name
    Default: ledger-app

  Environment:
    Type: String
    Description: Environment name
    Default: prod

  BuildPurpose:
    Type: String
    Description: logical purpose of produced artifact
    Default: db-init

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${BuildPurpose}/${Environment}"
      ImageTagMutability: MUTABLE
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Expire untagged images after 30 days",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 30
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

Outputs:
  RepositoryUri:
    Description: "ECR repository URI"
    Value: !GetAtt ECRRepository.RepositoryUri
    Export:
      Name: !Sub ${AppName}-${Environment}-${BuildPurpose}-ecr-uri