Parameters:
  AppName:
    Type: String
    Description: App name

  Environment:
    Type: String
    Description: Environment name

  LambdaLayerKey:
    Type: String
    Description: S3 bucket key used by lambda layer zip

  LambdaFunctionKey:
    Type: String
    Description: S3 bucket key used by lambda function zip

  InitSqlKey:
    Type: String
    Description: S3 bucket key used by sql db init

Resources:
  DatabaseInitFunctionRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        Policies:
          - PolicyName: DatabaseInitAccess
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action: s3:GetObject
                  Resource:
                    Fn::Sub:
                      - "arn:aws:s3:::${AssetBucket}/${InitSqlKey}"
                      - AssetBucket:
                          Fn::ImportValue: !Sub "${AppName}-${Environment}-asset-bucket"
                - Effect: Allow
                  Action: secretsmanager:GetSecretValue
                  Resource: "*"

  DatabaseInitLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: !Sub "${AppName}-${Environment}-db-init-layer"
      CompatibleRuntimes:
        - python3.11
      Content:
        S3Bucket:
          Fn::ImportValue: !Sub "${AppName}-${Environment}-asset-bucket"
        S3Key: !Ref LambdaLayerKey

  # DatabaseInitSecurityGroup:
  #   Type: AWS::EC2::SecurityGroup
  #   Properties:
  #     GroupDescription: Lambda SG
  #     VpcId: !Ref VPC
  #     SecurityGroupIngress: []
  #     SecurityGroupEgress:
  #       - IpProtocol: -1
  #         FromPort: 0
  #         ToPort: 0
  #         CidrIp: 0.0.0.0/0

  DatabaseInitFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AppName}-${Environment}-db-init"
      Runtime: python3.11
      Handler: handler.lambda_handler
      Role: !GetAtt DatabaseInitFunctionRole.Arn
      Timeout: 300
      Code:
        S3Bucket:
          Fn::ImportValue: !Sub "${AppName}-${Environment}-asset-bucket"
        S3Key: !Ref LambdaFunctionKey
      Layers:
        - !Ref DatabaseInitLayer
      Environment:
        Variables:
          DB_HOST: !Sub '{{resolve:ssm:/${AppName}/${Environment}/db/host}}'
          DB_USER: !Sub '{{resolve:ssm:/${AppName}/${Environment}/db/user}}'
          DB_NAME: !Sub '{{resolve:ssm:/${AppName}/${Environment}/db/database}}'
          DB_SECRET_NAME:
            Fn::ImportValue: !Sub "${AppName}-${Environment}-rds-master-secret-arn"
          SQL_BUCKET:
            Fn::ImportValue: !Sub "${AppName}-${Environment}-asset-bucket"
          SQL_KEY: !Ref InitSqlKey
      # PubliclyAccessible: false
      # VpcConfig:
      #   SubnetIds:
      #     - Fn::ImportValue:
      #         Fn::Sub: ${AppName}-${Environment}-public-subnet1-id
      #     - Fn::ImportValue:
      #         Fn::Sub: ${AppName}-${Environment}-public-subnet2-id
      #   SecurityGroupIds:
      #     - !Ref DatabaseInitSecurityGroup

  DatabaseInitFunctionTrigger:
    Type: Custom::DatabaseInitDatabase
    Properties:
      ServiceToken: !GetAtt DatabaseInitFunction.Arn