Description: Parametrik ECS Task Definition Template

Parameters:
  AppName:
    Type: String
    Description: App name

  Environment:
    Type: String
    Description: Environment name

  BuildPurpose:
    Type: String
    Description: logical purpose of produced artifact
    Default: db-init

Resources:
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AppName}-${Environment}-${BuildPurpose}-task-execution-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: SSMParameterAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameters
                  - ssm:GetParameter
                Resource:
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AppName}/${Environment}/db/*
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !ImportValue
                  Fn::Sub: ${AppName}-${Environment}-rds-master-secret-arn
              - Effect: Allow
                Action:
                  - kms:Decrypt
                Resource: '*'
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - !Sub
                      - "arn:aws:s3:::${BucketName}/*"
                      - BucketName:
                          Fn::ImportValue: !Sub "${AppName}-${Environment}-asset-bucket-name"
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${AppName}-${Environment}-${BuildPurpose}
      Cpu: '200'
      Memory: '150'
      NetworkMode: bridge
      RequiresCompatibilities:
        - EC2
      ExecutionRoleArn: !Ref TaskExecutionRole
      TaskRoleArn: !Ref TaskExecutionRole
      ContainerDefinitions:
        - Name: !Sub ${AppName}-${Environment}-${BuildPurpose}
          Image: 
            Fn::Sub:
              - "${ECR_URI}/${BuildPurpose}:latest"
              - ECR_URI:
                  Fn::ImportValue: !Sub ${AppName}-${Environment}-ecr-uri
          Command:
            - /bin/sh
            - '-c'
            - |
              aws s3 cp s3://$ASSET_BUCKET/db-init/sql/init.sql /tmp/init.sql && \
              until mysql -h $DATABASE_HOST -u $DATABASE_USER -p$DATABASE_PASS -e "select 1"; do
                sleep 5;
              done && \
              mysql -h $DATABASE_HOST -u $DATABASE_USER -p$DATABASE_PASS $DATABASE < /tmp/init.sql

          Cpu: 0
          Essential: true
          Secrets:
            - Name: ASSET_BUCKET
              ValueFrom:
                Fn::ImportValue:
                  Fn::Sub: "${AppName}-${Environment}-asset-bucket-name"
            - Name: DATABASE
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AppName}/${Environment}/db/database
            - Name: DATABASE_HOST
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AppName}/${Environment}/db/host
            - Name: DATABASE_HOST_PORT
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AppName}/${Environment}/db/port
            - Name: DATABASE_USER
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AppName}/${Environment}/db/user
            - Name: DATABASE_PASS
              ValueFrom: !Sub
                - '${SecretArn}:password::'
                - SecretArn: !ImportValue
                    Fn::Sub: ${AppName}-${Environment}-rds-master-secret-arn
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub /ecs/${AppName}-${Environment}
              awslogs-create-group: 'true'
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs