Parameters:
  AppName:
    Type: String
    Description: App name

  Environment:
    Type: String
    Description: Environment name

  DBName:
    Type: String
    Description: Database Name
    Default: ledger

  DBUser:
    Type: String
    Description: Database User Name
    Default: ledger

  DBPort:
    Type: String
    Description: Database User Name
    Default: 3306

Resources:
  DBNameSSMParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AppName}/${Environment}/db/database"
      Type: String
      Value: !Ref DBName

  DBPortSSMParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AppName}/${Environment}/db/port"
      Type: String
      Value: !Ref DBPort

  DBUserSSMParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AppName}/${Environment}/db/user"
      Type: String
      Value: !Ref DBUser
 
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: RDS Security Group
      GroupName: !Sub "${AppName}-${Environment}-rds-sg"
      VpcId: "vpc-04e9c5aee75bef483"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref DBPort
          ToPort: !Ref DBPort
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: "10"
      DBInstanceIdentifier: !Sub "${AppName}-${Environment}-db-instance"
      DBName: !Ref DBName
      DBInstanceClass: db.t4g.micro
      Engine: MySQL
      EngineVersion: "8.0.43"
      MasterUsername: !Ref DBUser
      ManageMasterUserPassword: true   # Create and store password in SecretManager
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup

  DBHostParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AppName}/${Environment}/db/host"
      Type: String
      Value: !GetAtt RDSInstance.Endpoint.Address

Outputs:
  RDSMasterSecretArn:
    Description: "RDS master user secret arn"
    Value: !GetAtt RDSInstance.MasterUserSecret.SecretArn
    Export:
      Name: !Sub "${AppName}-${Environment}-rds-master-secret-arn"