Parameters:
  AppName:
    Type: String
    Description: App name

  Environment:
    Type: String
    Description: Environment name

  DBPort:
    Type: Number
    Description: Database User Name

Resources:
  DBNameSSMParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AppName}/${Environment}/db/database"
      Type: String
      Value: !Ref AppName

  DBPortSSMParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AppName}/${Environment}/db/port"
      Type: String
      Value: !Ref DBPort

  DBUserSSMParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AppName}/${Environment}/db/user"
      Type: String
      Value: !Ref AppName

  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS
      SubnetIds:
        - Fn::ImportValue: !Sub ${AppName}-${Environment}-private-subnet1-id
        - Fn::ImportValue: !Sub ${AppName}-${Environment}-private-subnet2-id

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: "10"
      DBInstanceIdentifier: !Sub "${AppName}-${Environment}-db-instance"
      DBName: !Ref AppName
      DBInstanceClass: db.t4g.micro
      Engine: MySQL
      EngineVersion: "8.0.43"
      MasterUsername: !Ref AppName
      ManageMasterUserPassword: true   # Create and store password in SecretManager
      Port: !Ref DBPort
      PubliclyAccessible: false
      DBSubnetGroupName: !Ref RDSSubnetGroup
      VPCSecurityGroups:
        - Fn::ImportValue: !Sub "${AppName}-${Environment}-rds-sg-id"

  DBHostParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AppName}/${Environment}/db/host"
      Type: String
      Value: !GetAtt RDSInstance.Endpoint.Address

Outputs:
  RDSMasterSecretArn:
    Description: "RDS master user secret arn"
    Value: !GetAtt RDSInstance.MasterUserSecret.SecretArn
    Export:
      Name: !Sub "${AppName}-${Environment}-rds-master-secret-arn"