Parameters:
  AppName:
    Type: String
    Description: App name

  Environment:
    Type: String
    Description: Environment name

  DBName:
    Type: String
    Description: Database Name
    Default: ledger

  DBUser:
    Type: String
    Description: Database User Name
    Default: ledger

  DBPort:
    Type: String
    Description: Database User Name
    Default: 3306

Resources:
  RdsInstanceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://ledger-app-aws-iac.s3.eu-north-1.amazonaws.com/database/rds.yaml
      Parameters:
        AppName: !Ref AppName
        Environment: !Ref Environment
        DBName: !Ref DBName
        DBUser: !Ref DBUser
        DBPort: !Ref DBPort