version: "3.9"

services:
  db:
    build:
      context: ../../services/database
      dockerfile: Dockerfile
    image: ledger-app-db:local
    container_name: ledger-db
    environment:
      MYSQL_ROOT_PASSWORD: devroot
      MYSQL_DATABASE: ledger
      MYSQL_USER: ledger
      MYSQL_PASSWORD: ledgerpass
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ../assets/sql/init.sql:/docker-entrypoint-initdb.d/init.sql


  web:
    build:
      context: ../../services/web
      dockerfile: Dockerfile
    image: ledger-app-web:local
    container_name: ledger-web
    environment:
      DATABASE: ledger
      DATABASE_USER: ledger
      DATABASE_PASS: ledgerpass
      DATABASE_HOST: db
      DATABASE_HOST_PORT: 3306
    ports:
      - "80:80"
    depends_on:
      - db

volumes:
  db-data: