Parameters:
  AppName:
    Type: String
    Description: App name

  Environment:
    Type: String
    Description: Environment name

  DeploymentType:
    Type: String
    Description: Deployment tipi (bluegreen veya rolling)

  GithubConnectionArn:
    Type: String
    Description: Github Connection ARN

  SourceRepo:
    Type: String
    Description: owner/repo biciminde GitHub repo ID'si

  SourceBranch:
    Type: String

  ContainerPort:
    Type: Number

Resources:
  CodeBuildStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://ledger-app-aws-iac.s3.eu-north-1.amazonaws.com/pipeline/web/build-project.yaml
      Parameters:
        AppName: !Ref AppName
        Environment: !Ref Environment
        DeploymentType: !Ref DeploymentType
        GithubConnectionArn: !Ref GithubConnectionArn
        ContainerPort: !Ref ContainerPort

  CodePipelineServiceRole:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - CodeBuildStack
    Properties:
      TemplateURL: https://ledger-app-aws-iac.s3.eu-north-1.amazonaws.com/pipeline/web/pipeline-role.yaml
      Parameters:
        AppName: !Ref AppName
        Environment: !Ref Environment
        GithubConnectionArn: !Ref GithubConnectionArn
        DeploymentType: !Ref DeploymentType

  CodePipelineStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - CodePipelineServiceRole
    Properties:
      TemplateURL: https://ledger-app-aws-iac.s3.eu-north-1.amazonaws.com/pipeline/web/pipeline.yaml
      Parameters:
        AppName: !Ref AppName
        Environment: !Ref Environment
        DeploymentType: !Ref DeploymentType
        SourceRepo: !Ref SourceRepo
        SourceBranch: !Ref SourceBranch
        GithubConnectionArn: !Ref GithubConnectionArn