Resources:
  DatabaseInitLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DatabaseInitAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: s3:GetObject
                Resource: arn:aws:s3:::ledger-app-aws-iac/sql/*
              - Effect: Allow
                Action: secretsmanager:GetSecretValue
                Resource: "*"
  DatabaseInitLambda:
  Type: AWS::Lambda::Function
  Properties:
    FunctionName: !Sub "${AppName}-${Environment}-db-init"
    Runtime: python3.11
    Handler: lambda_function.lambda_handler
    Role: !GetAtt DatabaseInitLambdaRole.Arn
    Timeout: 300
    Code:
      S3Bucket: ledger-app-aws-iac
      S3Key: lambda/database-init-lambda.zip
    Environment:
      Variables:
        DB_HOST: !Sub '{{resolve:ssm:/${AppName}/${Environment}/db/host}}'
        DB_USER: !Sub '{{resolve:ssm:/${AppName}/${Environment}/db/user}}'
        DB_NAME: !Sub '{{resolve:ssm:/${AppName}/${Environment}/db/database}}'
        DB_SECRET_NAME: !Sub '${AppName}-${Environment}db-pass'
        SQL_BUCKET: ledger-app-aws-iac
        SQL_KEY: sql/init.sql

DatabaseInitTrigger:
  Type: Custom::DatabaseInitDatabase
  Properties:
    ServiceToken: !GetAtt DatabaseInitLambda.Arn
