AWSTemplateFormatVersion: '2010-09-09'
Description: CodeBuild project for ECS Pipeline

Parameters:
  AppName:
    Type: String
    Description: App name

  Environment:
    Type: String
    Description: Environment name

  DeploymentType:
    Type: String
    Description: Deployment Type (rolling or bluegreen)

  GithubConnectionArn:
    Type: String
    Description: Github Connection ARN

  ContainerPort:
    Type: Number

Conditions:
  IsRolling: !Equals [ !Ref DeploymentType, "rolling" ]

Resources:
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AppName}-${Environment}-build-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeBuildDeveloperAccess
      Policies:
        - PolicyName: AdditionalPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: AllowLogging
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/ecs/${AppName}-${Environment}:*"

              - Sid: AllowECRAccess
                Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                  - ecr:BatchGetImage
                  - ecr:PutImage
                Resource: "*"

              - Sid: AllowS3Access
                Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource: "*"

              - Sid: AllowSecretManagerAccess
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: "*"

        - PolicyName: GitHubConnectionAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - codestar-connections:GetConnectionToken
                  - codestar-connections:GetConnection
                  - codeconnections:GetConnectionToken
                  - codeconnections:GetConnection
                  - codeconnections:UseConnection
                Resource:
                  - !Ref GithubConnectionArn
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${AppName}-${Environment}-build-project"
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
        PrivilegedMode: true  # Eğer Docker build yapıyorsan gerekli
        EnvironmentVariables:
          - Name: AWS_REGION
            Value: !Ref AWS::Region
            Type: PLAINTEXT

          - Name: ACCOUNT_ID
            Value: !Ref AWS::AccountId
            Type: PLAINTEXT

          - Name: APP_NAME
            Value: !Ref AppName
            Type: PLAINTEXT

          - Name: ENVIRONMENT
            Value: !Ref Environment
            Type: PLAINTEXT

          - Name: REPO_NAME
            Value: !Sub "${AppName}-${Environment}-web-image"
            Type: PLAINTEXT

          - Name: ECR_URI
            Value: 
              Fn::ImportValue:
                Fn::Sub: ${AppName}-${Environment}-web-image-ecr-uri
            Type: PLAINTEXT

          - Name: TASK_DEFINITION_ARN
            Value:
              Fn::ImportValue:
                Fn::Sub: ${AppName}-${Environment}-task-definition-arn
            Type: PLAINTEXT

          - Name: TASK_DEFINITION_FAMILY
            Value: !Sub "${AppName}-${Environment}"
            Type: PLAINTEXT              

          - Name: TASK_EXECUTION_ROLE 
            Value:
              Fn::ImportValue:
                Fn::Sub: ${AppName}-${Environment}-ecs-task-executionrole-arn
            Type: PLAINTEXT
      
          - Name: CONTAINER_NAME
            Value: !Sub "${AppName}-${Environment}"
            Type: PLAINTEXT             

          - Name: CONTAINER_PORT
            Value: !Ref ContainerPort
            Type: PLAINTEXT

          - Name: DATABASE_PASS
            Value:
              Fn::ImportValue: !Sub "${AppName}-${Environment}-rds-master-secret-arn"

      Artifacts:
        Type: CODEPIPELINE 
        Packaging: ZIP
      Source:
        Type: CODEPIPELINE
        BuildSpec: !If
          - IsRolling
          - infrastructure/cicd/web-image/rolling-update/buildspec.yml
          - infrastructure/cicd/web-image/blue-green/buildspec.yml
      TimeoutInMinutes: 5

Outputs:
  CodeBuildProjectArn:
    Description: CodeBuild Project Arn
    Value: !GetAtt CodeBuildProject.Arn
    Export:
      Name: !Sub ${AppName}-${Environment}-build-project-arn